export { AboutHero } from '@/features/about/components/AboutHero'
export { AboutIntro } from '@/features/about/components/AboutIntro'
export { AboutShowreel } from '@/features/about/components/AboutShowreel'
export { AwardLogos } from '@/features/about/components/AwardLogos'
export { StatsCarousel } from '@/features/about/components/StatsCarousel'
export { ReviewsCarousel } from '@/features/about/components/ReviewsCarousel'
export { AwardsMarquee } from '@/features/about/components/AwardsMarquee'
